[profile.default]
src = "contracts"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc = "/opt/homebrew/bin/solc"
auto_detect_solc = false
optimizer = true
optimizer_runs = 200
evm_version = "paris"
offline = true

[rpc_endpoints]
somnia_mainnet = "${SOMNIA_RPC_MAINNET}"
somnia_testnet = "${SOMNIA_RPC_TESTNET}"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "thousands"
